# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messaging.proto',
  package='assignment1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmessaging.proto\x12\x0b\x61ssignment1\"\x94\x03\n\x03RFW\x12\x0e\n\x06RFW_ID\x18\x01 \x01(\x05\x12\x36\n\x0e\x42\x65nchmark_Type\x18\x02 \x01(\x0e\x32\x1e.assignment1.RFW.BenchmarkType\x12\x38\n\x0fWorkload_Metric\x18\x03 \x01(\x0e\x32\x1f.assignment1.RFW.WorkloadMetric\x12\x12\n\nBatch_Unit\x18\x04 \x01(\x05\x12\x10\n\x08\x42\x61tch_ID\x18\x05 \x01(\x05\x12\x12\n\nBatch_Size\x18\x06 \x01(\x05\"Y\n\rBenchmarkType\x12\x0e\n\nDVDTESTING\x10\x00\x12\x0f\n\x0b\x44VDTRAINING\x10\x01\x12\x12\n\x0eNDBENCHTESTING\x10\x02\x12\x13\n\x0fNDBENCHTRAINING\x10\x03\"v\n\x0eWorkloadMetric\x12\x19\n\x15\x43PUUTILIZATIONAVERAGE\x10\x00\x12\x14\n\x10NETWORKINAVERAGE\x10\x01\x12\x15\n\x11NETWORKOUTAVERAGE\x10\x02\x12\x1c\n\x18MEMORYUTILIZATIONAVERAGE\x10\x03\"A\n\x03RFD\x12\x0e\n\x06RFW_ID\x18\x01 \x01(\x05\x12\x15\n\rlast_Batch_ID\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x61tasamples\x18\x03 \x03(\x01\x62\x06proto3'
)



_RFW_BENCHMARKTYPE = _descriptor.EnumDescriptor(
  name='BenchmarkType',
  full_name='assignment1.RFW.BenchmarkType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DVDTESTING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DVDTRAINING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NDBENCHTESTING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NDBENCHTRAINING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=228,
  serialized_end=317,
)
_sym_db.RegisterEnumDescriptor(_RFW_BENCHMARKTYPE)

_RFW_WORKLOADMETRIC = _descriptor.EnumDescriptor(
  name='WorkloadMetric',
  full_name='assignment1.RFW.WorkloadMetric',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CPUUTILIZATIONAVERAGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NETWORKINAVERAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NETWORKOUTAVERAGE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEMORYUTILIZATIONAVERAGE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=319,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_RFW_WORKLOADMETRIC)


_RFW = _descriptor.Descriptor(
  name='RFW',
  full_name='assignment1.RFW',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RFW_ID', full_name='assignment1.RFW.RFW_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Benchmark_Type', full_name='assignment1.RFW.Benchmark_Type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Workload_Metric', full_name='assignment1.RFW.Workload_Metric', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Batch_Unit', full_name='assignment1.RFW.Batch_Unit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Batch_ID', full_name='assignment1.RFW.Batch_ID', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Batch_Size', full_name='assignment1.RFW.Batch_Size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RFW_BENCHMARKTYPE,
    _RFW_WORKLOADMETRIC,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=437,
)


_RFD = _descriptor.Descriptor(
  name='RFD',
  full_name='assignment1.RFD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RFW_ID', full_name='assignment1.RFD.RFW_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_Batch_ID', full_name='assignment1.RFD.last_Batch_ID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datasamples', full_name='assignment1.RFD.datasamples', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=504,
)

_RFW.fields_by_name['Benchmark_Type'].enum_type = _RFW_BENCHMARKTYPE
_RFW.fields_by_name['Workload_Metric'].enum_type = _RFW_WORKLOADMETRIC
_RFW_BENCHMARKTYPE.containing_type = _RFW
_RFW_WORKLOADMETRIC.containing_type = _RFW
DESCRIPTOR.message_types_by_name['RFW'] = _RFW
DESCRIPTOR.message_types_by_name['RFD'] = _RFD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RFW = _reflection.GeneratedProtocolMessageType('RFW', (_message.Message,), {
  'DESCRIPTOR' : _RFW,
  '__module__' : 'messaging_pb2'
  # @@protoc_insertion_point(class_scope:assignment1.RFW)
  })
_sym_db.RegisterMessage(RFW)

RFD = _reflection.GeneratedProtocolMessageType('RFD', (_message.Message,), {
  'DESCRIPTOR' : _RFD,
  '__module__' : 'messaging_pb2'
  # @@protoc_insertion_point(class_scope:assignment1.RFD)
  })
_sym_db.RegisterMessage(RFD)


# @@protoc_insertion_point(module_scope)
